# -*- coding: utf-8 -*-
"""Tickets_interactive_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xif3n_6Mojuhrf_SYxHAswjj98qTfbSa
"""

import pandas as pd

# Load the dataset
df = pd.read_csv('/content/dataset.csv')

def get_ticket_details(ticket_id):
    """
    Returns the row, seat, and gate details for a given ticket_id.

    Parameters:
        ticket_id (str): The ticket identifier, e.g., "T000001".

    Returns:
        dict or str: A dictionary with the ticket details if found, otherwise a message.
    """
    # Filter the DataFrame to find the row matching the given ticket_id
    ticket_data = df[df['Ticket_ID'] == ticket_id]

    # Check if the ticket exists in the dataset
    if ticket_data.empty:
        return f"No ticket found with Ticket_ID: {ticket_id}"

    # Extract the details from the first (and only) matching row
    details = ticket_data.iloc[0]
    return {
        'Row': details['Row'],
        'Seat': details['Seat'],
        'Gate': details['Gate']
    }

# Prompt the user to input a ticket number
ticket_number = input("Please enter the ticket number (e.g., T000001): ")

# Retrieve and display the ticket details
details = get_ticket_details(ticket_number)
print(details)